# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ecad69e051407678829e37f2a335262cee74831f3db4dddf5a00d0ce9a126d68b0432523ed290a6097c7f23a698879796197668d953310cea69bedfcc81f737

test:
  secret_key_base: c0c8c715846cdd42c27b13d6bde89ecac1867355696a920f1500e07242df6c872f3d13936c318d9e7f53ab5b3f2ec18775f7f5d154598edaebd61c0fe1f5adba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
